name: infra_pitch_deck
description: "Infra research presentation deck"
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  flex_color_scheme: ^8.3.1
  flutter_animate: ^4.5.2
  flutter_deck: ^0.22.0
  google_fonts: ^6.3.2
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/portfolio/shveya/
    - assets/images/portfolio/soulwi/
    - assets/images/portfolio/phil/
    - assets/images/portfolio/smysl/
